### ISSUE TITLE
Windows-Installer: Node.js und Ports prüfen

### ISSUE THREAD

**Issue by DEV2DEV-DE** [ioBroker/ioBroker.build#1]
Beim Testen des Installers bin ich über 2 Fallstricke gestolpert:

1. Es wird nicht geprüft, ob evtl. bereits Node.js in einer passenden Version installiert ist.
Das lässt sich in InnoSetup z.B. über die Registry prüfen:
`var`
`  version: string;`
`if RegKeyExists(HKEY_LOCAL_MACHINE, 'SOFTWARE\Node.js') then`
`begin`
`  if RegQueryStringValue(HKEY_LOCAL_MACHINE, 'SOFTWARE\Node.js', 'Version', version) then`
`  begin`
`    MsgBox('Node.js has already been installed. Version: ' + version, mbInformation, MB_OK);`
`  end;`
`end;`

2. Wenn die Ports (9000 + 9001) bereits verwendet werden, schlägt `npm install` fehl und bei der Installation bleibt "das Messer im Schwein stecken". Es bleibt dann eine unvollständige Installation zurück.
Auch die verwendeten Ports ließen sich prüfen und ggf.  über eine zwischengeschobene Seite in InnoSetup ändern:
https://stackoverflow.com/questions/21701847/how-to-check-if-port-is-usable-in-inno-setup

**Comment by DEV2DEV-DE** [comment]
Das Problem mit Node.js rührt vermutlich daher, dass (zumindest auf meinem System) Node in einem anderen als dem erwarteten Verzeichnis installiert ist.
Erwartet wird im Setup-Script `FileExists(ExpandConstant('{commonpf64}\nodejs\node.exe'));`
Installiert ist es bei mir hier: `C:\Program Files\nodejs`.
Das Setup bekommt also gar nicht mit, dass Node.js bereits installiert ist und packt sein eigenes hinzu.

Möglicherweise ist der Weg über die Registry hier sicherer.

**Comment by Gaspode69** [comment]
Ich denke nicht, dass der Registry Ansatz für die Ermittlung von node.js optimal ist. Letztendlich kommt es ja darauf an, welche node version im weiteren Installationsverlauf aufgerufen bzw. verwendet wird, und das ist abhängig von der Path Variablen. Im späteren Verlauf der Installation wird ja - wenn ich das richtig sehe - auch einfach "node" ohne konkrete Pfadangabe aufgerufen.
Lange Rede kurzer Sinn:
Es gibt einen guten Artikel in Stackoverflow, der eine Lösung parat hat (sogar anhand von node.js als Beispiel):
https://stackoverflow.com/questions/52385399/inno-setup-check-version-of-external-application

**Comment by Gaspode69** [comment]
Ich hab mal einen PR angelegt, wie das aussehen könnte: #2 
Ich bitte um Nachsicht, das ist mein erster Kontakt zu innoSetup.

**Comment by DEV2DEV-DE** [comment]
> Ich hab mal einen PR angelegt, wie das aussehen könnte: #2 Ich bitte um Nachsicht, das ist mein erster Kontakt zu innoSetup.

Versuch macht klug ;-) Solange es stabil funktioniert und das Ziel erreicht wird, ist der Weg dahin ja zweitrangig.

**Comment by Gaspode69** [comment]
Ach ja: Die Prüfung der Node Version war schon im Script berücksichtigt, das habe ich deshalb so gelassen, wie es war.

**Comment by DEV2DEV-DE** [comment]
Ich habe mal quick & dirty eine Prüfung der Ports eingebaut. [#4](https://github.com/ioBroker/ioBroker.build/pull/4)
Sollte einer der Ports (9000, 9001) aktiv verwendet werden, erfolgt eine Meldung und die Installation wird abgebrochen.
Das verhindert zumindest mal die unvollständigen Installationen.
Man müsste sich dann mal darauf einigen, was passieren soll wenn die Ports belegt sind.

**Comment by Apollon77** [comment]
Wow cool ... 

Was passieren soll? Ich bin aktuell für "user soll sie frei machen".

**Comment by DEV2DEV-DE** [comment]
> Ich bin aktuell für "user soll sie frei machen".

Ich wäre auch dafür. Beugt späteren Problemen vor, wenn der ioBroker mit anderen Ports betrieben würde.
Dafür sollte man schon genau wissen, was man da tut.

**Comment by Gaspode69** [comment]
Sehe ich auch so. Am Einfachsten Installer mit Hinweis auf belegte Ports abbrechen und den User auffordern, diese freizugeben. 
Sollten die anderen benötigten Ports nicht auch besser geprüft werden (8081, 8082,...?)

**Comment by Apollon77** [comment]
Also senn maximal Admin aka 8081 ... alle anderen ports sind per admin konfigurierbar

**Comment by DEV2DEV-DE** [comment]
> Sollten die anderen benötigten Ports nicht auch besser geprüft werden (8081, 8082,...?)

Naja, ob der Admin jetzt unter 8081 oder einem anderen Port erreichbar ist, finde ich persönlich jetzt nicht so kritisch.
Aber da das erst nach der Einrichtung zu ändern wäre und der Windows-Anwender wohl meist eher zu den Einsteigern zählt, würde ich zumindest 8081 auch in die Prüfung aufnehmen.
Vis etc. kommt ja - wie @Apollon77 schon schreibt - erst später ins Spiel.

Die Meldung habe ich auch noch lokalisiert - die russische Version muss dann aber @GermanBluefox beisteuern ;-)
PR kommt noch ...

**Comment by Gaspode69** [comment]
> Aber da das erst nach der Einrichtung zu ändern wäre und der Windows-Anwender wohl meist eher zu den Einsteigern zählt, würde ich zumindest 8081 auch in die Prüfung aufnehmen.

Unbedingt. Schließlich wird am Ende der Installation ja direkt http://localhost:8081 geöffnet

**Comment by DEV2DEV-DE** [comment]
Den PR habe ich erweitert:
Das Ganze ist nun lokalisiert und wird nicht mehr als simple MessageBox sondern als separate Seite im Setup-Wizard angezeigt.
![grafik](https://user-images.githubusercontent.com/95883579/212774296-62a61684-d79f-487e-a682-dfd50c430926.png)

**Comment by DEV2DEV-DE** [comment]
Nur so als Anmerkung - soll keine Kritik sein:
Wenn der master-branch dann wieder aktuell ist, würde ich im Install-Script noch etwas aufräumen.
Es braucht z.B. keine eigene `function`, um die Texte für die Abschlussseite zu holen. Das könnte man eleganter über die `CustomMessages` lösen. Die tauchen dann auch als solche in z.B. Inno-Script-Studio auf.
Außerdem gilt für mein Team z.B. die Regel, keinen auskommentierten Code zu hinterlassen. Dafür ist schließlich die Quellcodeverwaltung da ... was man nochmal braucht, holt man sich aus dem Repo.
Ist zwar "nur" ein kleines Install-Script, aber ich persönlich habe auch sowas gerne "aufgeräumt".

**Comment by GermanBluefox** [comment]
https://github.com/ioBroker/ioBroker.build/pull/4 ist gemerged. Kommt noch was oder kann ich publishen?

**Comment by Gaspode69** [comment]
@GermanBluefox 
wie mit @Apollon77 besprochen baue ich den Installer gerade komplett um, dann wird auch die Port Prüfung anders umgesetzt sein.
