### ISSUE TITLE
Frage/Diskussion: Ist der Windows Installer in dieser Form wirklich sinnvoll?

### ISSUE THREAD

**Issue by Gaspode69** [ioBroker/ioBroker.build#5]
Ich möchte nochmal kurz einen Schritt zurück gehen und nochmal grundsätzlich über Sinn und Funktion eines Windows Installers nachdenken.
Inzwischen wurde die eigentliche ioBroker Installation ja auf einen npx One-Liner verkürzt. Der Installer installiert daher (derzeit) lediglich Node.js (und zwar in einer festgelegten Version, die er mitbringt) und ruft anschließend die npx Installation auf, die den akzuellen ioBroker installiert.
Wenn ich diesen Installer jetzt in einem halben Jahr verwende, wird eine veraltete Node.js Version und der neueste ioBroker installiert.
Ist das so wirklich sinnvoll?
Ich fände einen Installer sinnvoll, der die zum Installationszeitpunkt aktuellen Komponenten ermittelt (derzeit nur Node.js, in Zukunft evt. auch Python, MS Build Tools, etc.), diese herunterlädt, instaliert/aktualisiert und dann ioBroker per npx installiert.

Ich stelle mir das im ersten Schritt so vor:
* Voraussetzungen prüfen (freie Ports, etc.)
* Ermitteln, ob und welche Node.JS Version installiert ist
* Ermitteln, ob ioBroker bereits installiert ist und in welcher Version
* Ermitteln, welche Node.js Version die passende ist (abhängig ob ioBroker bereits installiert ist und in welcher Version)
* ggfs. ioBroker anhalten
* Download und Installieren/Aktualisieren von Node.js
* Wenn erfoderlich ioBroker per npx installieren (bzw. ggfs auf Wunsch "Fix"en)

Die einzelnen lassen sich mit Inno Setup recht einfach implementieren. Außer der Ermittlung der passenden Node.js Version habe ich das bereits ausprobiert. 

In Zukunft könnte man dieses Konzept um weitere Komponenten erweitern, z.B. MS Build Tools, Python, etc.

Bitte versteht das nicht als Aufforderung an euer ohnehin stark belastetes Team, das umzusetzen. Ich (und bestimmt noch ein paar andere) wäre bereit, den Großteil beizusteuern. Alledrings fehlt mir halt etwas Know How, derzeit z.B. wie man die aktuell empfohlene Nodes Version ermitteln kann.

Ich kann aber auch verstehen, wenn es nur darum geht einen einfachen Installer zu haben, um die Berührungsängste einiger Windows User zu besiegen. Denn wenn man ehrlich ist, braucht man mit der aktuellen npx-Installationslösung für Windows nicht mehr wirklich einen Installer.

**Comment by DEV2DEV-DE** [comment]
Wirklich brauchen tut man den Installer in seiner jetzigen Form eigentlich kaum. "Nicht" würde ich nicht sagen wollen, denn wie Du vermute auch ich, dass gerade Einsteiger mit einem Installer weniger Berührungsängste haben. Ist ja eigentlich aktuell nicht viel mehr als ein "Wrapper" um das npx-Install.

Wir machen das bei uns so, dass die jeweils aktuellen Versionsnummern über einen http-Request von einem Server gelesen werden. Da die empfohlenen Versionen für Node und NPM ja für ioBroker spezielle sind und auf keinen Fall immer die neuesten verwendet werden sollten, müsste die Quelle für die empfohlenen Versionen also irgendwo im ioBroker Universum zu finden sein.
Das muss dann aber auch jemand verwalten.

Bei der Erweiterung des Installers wäre ich dabei - jedenfalls so wie es Beruf und Familie zulassen. Beim Thema "Beruf" hätte HomeOffice da aktuell gewisse Vorteile ;-)

**Comment by Gaspode69** [comment]
> Da die empfohlenen Versionen für Node und NPM ja für ioBroker spezielle sind und auf keinen Fall immer die neuesten verwendet werden sollten, müsste die Quelle für die empfohlenen Versionen also irgendwo im ioBroker Universum zu finden sein.
Das muss dann aber auch jemand verwalten.

Ich habe vermutet, da gibt es schon was, da es der Info Adapter ja anzeigt. Allerdings scheint es so zu sein, dass die aktuelle Major Node Version im iobroker.info Adapter [hier fest codiert](https://raw.githubusercontent.com/iobroker-community-adapters/ioBroker.info/master/admin/lib/data/infoData.json) ist und dann die jeweils neueste verfügbare Version als "Empfohlen" angezeigt wird.

Das könnte man nachbauen, wenn auch das Arbeiten mit JSON etwas umständlich in inno setup ist.

Ich persönlich würde jetzt erst einmal abwarten, ob sich jemand von ioBroker Team äußert und wie die Sache gesehen wird.

Oh, ich merke gerade, dass sich das etwas fordernd anhört. Deshalb sicherheitshalber ein Disclaimer: Nur kein Stress und keine Hektik!

**Comment by Gaspode69** [comment]
Ist ja jetzt geklärt.
