### ISSUE TITLE
License text for new Windows installer

### ISSUE THREAD

**Issue by Gaspode69** [ioBroker/ioBroker.build#6]
Hi,
@GermanBluefox 
I wonder if the license text for the Windows installer used by Stabilostick is still OK to be used for a new version of the installer. Can you please verify? Don't be shocked, it is a bit long. ;-)

[Lizenz.txt](https://github.com/ioBroker/ioBroker.build/files/10833819/Lizenz.txt)

**Comment by GermanBluefox** [comment]
Ja, passt
